# NETFLIX CONTENT INTELLIGENCE & GLOBAL STREAMING  ANALYTICS

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("Netflix_Content_Intelligence_&_Global_Streaming_Analytics_dataset.csv")

 ## Total Rows & Columns

In [3]:
df.shape

(1000, 10)

## Column Names

In [4]:
df.columns

Index(['Title_ID', 'Title', 'Type', 'Country', 'Genre', 'Rating',
       'Release_Year', 'Date_Added', 'Duration_Minutes', 'IMDb_Rating'],
      dtype='object')

## First 10 Rows

In [5]:
df.head(10)

,Title_ID,Title,Type,Country,Genre,Rating,Release_Year,Date_Added,Duration_Minutes,IMDb_Rating
0,NF0001,Netflix Title 1,Movie,United States,Documentary,TV-14,2017,2021-07-25,154,5.9
1,NF0002,Netflix Title 2,Movie,Brazil,Sci-Fi,TV-MA,2010,2021-01-18,87,6.4
2,NF0003,Netflix Title 3,Movie,Germany,Thriller,TV-PG,2023,2022-06-21,117,7.9
3,NF0004,Netflix Title 4,Movie,United Kingdom,Sci-Fi,PG-13,2018,2021-09-28,87,9.3
4,NF0005,Netflix Title 5,TV Show,India,Comedy,R,2013,2024-01-10,6,7.9
5,NF0006,Netflix Title 6,Movie,France,Animation,TV-MA,2022,2020-11-18,130,6.7
6,NF0007,Netflix Title 7,TV Show,Brazil,Thriller,TV-PG,2012,2020-07-06,4,8.6
7,NF0008,Netflix Title 8,Movie,Canada,Comedy,R,2018,2025-01-31,141,8.8
8,NF0009,Netflix Title 9,Movie,South Korea,Romance,TV-14,2018,2020-10-19,137,8.0
9,NF0010,Netflix Title 10,Movie,United Kingdom,Crime,R,2018,2022-06-18,147,6.8

## Last 9  Rows

In [6]:
df.tail(9)

,Title_ID,Title,Type,Country,Genre,Rating,Release_Year,Date_Added,Duration_Minutes,IMDb_Rating
991,NF0992,Netflix Title 992,Movie,India,Animation,TV-14,2025,2022-11-22,103,8.6
992,NF0993,Netflix Title 993,Movie,Germany,Documentary,TV-14,2013,2020-07-25,178,9.3
993,NF0994,Netflix Title 994,TV Show,India,Comedy,PG,2013,2020-06-20,9,5.9
994,NF0995,Netflix Title 995,Movie,Canada,Romance,TV-14,2019,2024-12-13,157,7.5
995,NF0996,Netflix Title 996,Movie,United Kingdom,Romance,PG-13,2014,2021-05-18,168,6.3
996,NF0997,Netflix Title 997,TV Show,United States,Thriller,R,2020,2023-03-20,9,6.2
997,NF0998,Netflix Title 998,TV Show,South Korea,Sci-Fi,PG-13,2017,2021-09-12,9,7.2
998,NF0999,Netflix Title 999,Movie,United Kingdom,Sci-Fi,R,2023,2025-02-22,169,7.6
999,NF1000,Netflix Title 1000,TV Show,United States,Crime,TV-14,2010,2025-10-20,2,5.8

## Random Rows

In [7]:
df.sample(10)

,Title_ID,Title,Type,Country,Genre,Rating,Release_Year,Date_Added,Duration_Minutes,IMDb_Rating
974,NF0975,Netflix Title 975,TV Show,United Kingdom,Thriller,TV-14,2012,2022-11-28,2,7.2
918,NF0919,Netflix Title 919,Movie,Spain,Thriller,TV-MA,2014,2022-02-25,63,6.5
304,NF0305,Netflix Title 305,TV Show,Japan,Action,TV-14,2020,2022-07-31,7,7.8
131,NF0132,Netflix Title 132,TV Show,Japan,Drama,TV-PG,2022,2023-01-29,1,7.8
954,NF0955,Netflix Title 955,Movie,United Kingdom,Drama,R,2018,2021-10-31,150,7.4
209,NF0210,Netflix Title 210,Movie,France,Crime,TV-PG,2015,2021-07-06,68,8.4
2,NF0003,Netflix Title 3,Movie,Germany,Thriller,TV-PG,2023,2022-06-21,117,7.9
16,NF0017,Netflix Title 17,TV Show,United States,Documentary,PG,2015,2025-09-10,2,9.0
811,NF0812,Netflix Title 812,TV Show,Germany,Crime,R,2017,2021-12-15,10,8.3
757,NF0758,Netflix Title 758,Movie,Canada,Romance,PG-13,2019,2024-11-15,151,9.4

## Data Type Check

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Title_ID          1000 non-null   object
 1   Title             1000 non-null   object
 2   Type              1000 non-null   object
 3   Country           1000 non-null   object
 4   Genre             1000 non-null   object
 5   Rating            1000 non-null   object
 6   Release_Year      1000 non-null   int64
 7   Date_Added        1000 non-null   object
 8   Duration_Minutes  1000 non-null   int64
 9   IMDb_Rating       1000 non-null   float64
dtypes: float64(1), int64(2), object(7)
memory usage: 78.3+ KB

## Statistical Summary

In [9]:
df.describe()

       Release_Year  Duration_Minutes  IMDb_Rating
count    1000.00000        1000.00000   1000.00000
mean     2017.65000          61.06900      7.50750
std         4.55832          62.75352      1.13573
min      2010.00000           1.00000      5.50000
25%      2014.00000           5.00000      6.60000
50%      2018.00000          10.00000      7.40000
75%      2022.00000         118.00000      8.50000
max      2025.00000         180.00000      9.50000

## Missing Values column wise

In [10]:
df.isnull().sum()

Title_ID            0
Title               0
Type                0
Country             0
Genre               0
Rating              0
Release_Year        0
Date_Added          0
Duration_Minutes    0
IMDb_Rating         0
dtype: int64

## Percentage

In [11]:
(df.isnull().sum()/len(df))*100

Title_ID            0.0
Title               0.0
Type                0.0
Country             0.0
Genre               0.0
Rating              0.0
Release_Year        0.0
Date_Added          0.0
Duration_Minutes    0.0
IMDb_Rating         0.0
dtype: float64

## Duplicate Records

In [12]:
df.duplicated().sum()

np.int64(0)

## Duplicate Rows Show

In [13]:
df[df.duplicated()]

Empty DataFrame
Columns: [Title_ID, Title, Type, Country, Genre, Rating, Release_Year, Date_Added, Duration_Minutes, IMDb_Rating]
Index: []

## Unique Values

In [14]:
df.nunique()

Title_ID            1000
Title               1000
Type                   2
Country               10
Genre                 10
Rating                 6
Release_Year          16
Date_Added           800
Duration_Minutes     130
IMDb_Rating           41
dtype: int64

## Country Analysis

In [15]:
df["Country"].value_counts()

Country
France            122
United Kingdom    118
Germany           110
United States     101
Brazil            100
South Korea        98
India              94
Japan              92
Spain              83
Canada             82
Name: count, dtype: int64

In [16]:
df["Country"].value_counts().head(4)

Country
France            122
United Kingdom    118
Germany           110
United States     101
Name: count, dtype: int64

## Genre Analysis

In [17]:
df["Genre"].value_counts()

Genre
Animation      117
Crime          108
Documentary    105
Comedy         103
Horror          98
Romance         98
Drama           98
Action          94
Thriller        93
Sci-Fi          86
Name: count, dtype: int64

In [18]:
df["Genre"].mode()

0    Animation
Name: Genre, dtype: object

## Movie vs TV Show

In [19]:
df["Type"].value_counts()

Type
TV Show    518
Movie      482
Name: count, dtype: int64

In [20]:
df["Type"].value_counts(normalize=True)*100

Type
TV Show    51.8
Movie      48.2
Name: proportion, dtype: float64

## Rating Analysis

In [21]:
df["Rating"].value_counts()

Rating
R        176
TV-MA    171
TV-PG    170
PG-13    165
PG       160
TV-14    158
Name: count, dtype: int64

## IMDb Analysis

In [22]:
df["IMDb_Rating"].mean()

np.float64(7.5075)

In [23]:
df["IMDb_Rating"].min()

5.5

In [24]:
df["IMDb_Rating"].max()

9.5

## Top Rated Content

In [25]:
df.nlargest(10,"IMDb_Rating")

,Title_ID,Title,Type,Country,Genre,Rating,Release_Year,Date_Added,Duration_Minutes,IMDb_Rating
12,NF0013,Netflix Title 13,TV Show,Brazil,Sci-Fi,PG,2022,2024-01-22,4,9.5
21,NF0022,Netflix Title 22,TV Show,Canada,Animation,TV-PG,2016,2023-06-30,7,9.5
37,NF0038,Netflix Title 38,TV Show,France,Romance,TV-MA,2010,2025-02-20,10,9.5
119,NF0120,Netflix Title 120,TV Show,United States,Romance,TV-PG,2025,2024-04-10,7,9.5
268,NF0269,Netflix Title 269,TV Show,Brazil,Horror,TV-MA,2020,2023-03-11,8,9.5
276,NF0277,Netflix Title 277,Movie,Canada,Action,R,2014,2025-02-06,155,9.5
412,NF0413,Netflix Title 413,TV Show,India,Horror,PG,2018,2020-11-03,1,9.5
450,NF0451,Netflix Title 451,Movie,Canada,Thriller,TV-14,2011,2024-09-30,70,9.5
469,NF0470,Netflix Title 470,TV Show,Germany,Horror,R,2013,2020-01-31,9,9.5
612,NF0613,Netflix Title 613,Movie,France,Drama,TV-14,2023,2025-08-08,77,9.5

  ## Duration Analysis

In [26]:
df["Duration_Minutes"].mean()

np.float64(61.069)

In [27]:
df.nlargest(10,"Duration_Minutes")

,Title_ID,Title,Type,Country,Genre,Rating,Release_Year,Date_Added,Duration_Minutes,IMDb_Rating
258,NF0259,Netflix Title 259,Movie,Canada,Documentary,PG,2019,2022-07-10,180,9.4
293,NF0294,Netflix Title 294,Movie,Spain,Animation,R,2011,2023-11-11,180,8.1
335,NF0336,Netflix Title 336,Movie,Brazil,Animation,TV-14,2010,2025-03-05,180,8.3
38,NF0039,Netflix Title 39,Movie,India,Animation,TV-14,2018,2021-06-26,179,6.9
113,NF0114,Netflix Title 114,Movie,France,Comedy,TV-PG,2014,2025-08-03,179,8.4
283,NF0284,Netflix Title 284,Movie,Spain,Romance,TV-PG,2012,2020-09-03,179,9.1
344,NF0345,Netflix Title 345,Movie,India,Drama,PG-13,2013,2021-11-04,179,9.4
431,NF0432,Netflix Title 432,Movie,United Kingdom,Horror,PG-13,2017,2021-03-02,179,7.5
924,NF0925,Netflix Title 925,Movie,South Korea,Romance,PG,2022,2022-08-24,179,7.2
18,NF0019,Netflix Title 19,Movie,Brazil,Romance,R,2010,2021-04-03,178,7.0

In [28]:
df.nsmallest(10,"Duration_Minutes")

,Title_ID,Title,Type,Country,Genre,Rating,Release_Year,Date_Added,Duration_Minutes,IMDb_Rating
45,NF0046,Netflix Title 46,TV Show,Brazil,Animation,TV-14,2023,2021-06-06,1,6.7
68,NF0069,Netflix Title 69,TV Show,Spain,Romance,PG,2024,2024-08-30,1,6.3
109,NF0110,Netflix Title 110,TV Show,Germany,Drama,TV-PG,2024,2024-08-19,1,6.3
131,NF0132,Netflix Title 132,TV Show,Japan,Drama,TV-PG,2022,2023-01-29,1,7.8
140,NF0141,Netflix Title 141,TV Show,Japan,Sci-Fi,TV-MA,2014,2020-07-04,1,6.7
162,NF0163,Netflix Title 163,TV Show,Germany,Horror,PG,2010,2022-12-31,1,6.2
199,NF0200,Netflix Title 200,TV Show,Canada,Sci-Fi,TV-MA,2021,2022-07-08,1,6.8
210,NF0211,Netflix Title 211,TV Show,United States,Documentary,TV-14,2011,2022-03-28,1,6.8
211,NF0212,Netflix Title 212,TV Show,Germany,Sci-Fi,PG,2025,2022-11-03,1,8.5
254,NF0255,Netflix Title 255,TV Show,United Kingdom,Thriller,TV-MA,2013,2022-02-20,1,7.3

## Release Year Analysis

In [29]:
df["Release_Year"].value_counts()

Release_Year
2017    74
2020    74
2025    71
2013    71
2022    67
2023    65
2012    64
2019    63
2016    62
2014    60
2018    59
2011    58
2024    57
2015    56
2021    50
2010    49
Name: count, dtype: int64

## GroupBy Analysis

In [30]:
df.groupby("Genre")["IMDb_Rating"].mean()

Genre
Action         7.361702
Animation      7.437607
Comedy         7.722330
Crime          7.312037
Documentary    7.678095
Drama          7.531633
Horror         7.423469
Romance        7.537755
Sci-Fi         7.559302
Thriller       7.522581
Name: IMDb_Rating, dtype: float64

In [31]:
df.groupby("Country")["Title_ID"].count()

Country
Brazil            100
Canada             82
France            122
Germany           110
India              94
Japan              92
South Korea        98
Spain              83
United Kingdom    118
United States     101
Name: Title_ID, dtype: int64

In [32]:
df.groupby("Genre")["Duration_Minutes"].mean()

Genre
Action         62.255319
Animation      62.760684
Comedy         62.951456
Crime          60.231481
Documentary    54.019048
Drama          61.520408
Horror         57.459184
Romance        61.173469
Sci-Fi         70.046512
Thriller       59.505376
Name: Duration_Minutes, dtype: float64

In [33]:
df.groupby(
["Country","Genre"]
)["Title_ID"].count()

Country        Genre
Brazil         Action         13
               Animation      12
               Comedy          7
               Crime           9
               Documentary    10
                              ..
United States  Drama          12
               Horror          7
               Romance         9
               Sci-Fi          8
               Thriller       10
Name: Title_ID, Length: 100, dtype: int64

In [34]:
df.groupby(
["Country","Rating"]
)["Title_ID"].count()

Country         Rating
Brazil          PG        19
                PG-13     16
                R         16
                TV-14     16
                TV-MA     14
                TV-PG     19
Canada          PG        10
                PG-13     18
                R         16
                TV-14     17
                TV-MA      7
                TV-PG     14
France          PG        17
                PG-13     17
                R         15
                TV-14     25
                TV-MA     23
                TV-PG     25
Germany         PG        20
                PG-13     13
                R         16
                TV-14     18
                TV-MA     23
                TV-PG     20
India           PG        17
                PG-13     16
                R         16
                TV-14     15
                TV-MA     14
                TV-PG     16
Japan           PG        13
                PG-13     14
                R         18
                TV-14     11
                TV-MA     19
                TV-PG     17
South Korea     PG        14
                PG-13     18
                R         17
                TV-14     15
                TV-MA     15
                TV-PG     19
Spain           PG        17
                PG-13     13
                R         17
                TV-14      5
                TV-MA     21
                TV-PG     10
United Kingdom  PG        19
                PG-13     21
                R         19
                TV-14     20
                TV-MA     19
                TV-PG     20
United States   PG        14
                PG-13     19
                R         26
                TV-14     16
                TV-MA     16
                TV-PG     10
Name: Title_ID, dtype: int64

## Filtering

In [35]:
df[df["Type"]=="Movie"]

,Title_ID,Title,Type,Country,Genre,Rating,Release_Year,Date_Added,Duration_Minutes,IMDb_Rating
0,NF0001,Netflix Title 1,Movie,United States,Documentary,TV-14,2017,2021-07-25,154,5.9
1,NF0002,Netflix Title 2,Movie,Brazil,Sci-Fi,TV-MA,2010,2021-01-18,87,6.4
2,NF0003,Netflix Title 3,Movie,Germany,Thriller,TV-PG,2023,2022-06-21,117,7.9
3,NF0004,Netflix Title 4,Movie,United Kingdom,Sci-Fi,PG-13,2018,2021-09-28,87,9.3
5,NF0006,Netflix Title 6,Movie,France,Animation,TV-MA,2022,2020-11-18,130,6.7
...,...,...,...,...,...,...,...,...,...,...
991,NF0992,Netflix Title 992,Movie,India,Animation,TV-14,2025,2022-11-22,103,8.6
992,NF0993,Netflix Title 993,Movie,Germany,Documentary,TV-14,2013,2020-07-25,178,9.3
994,NF0995,Netflix Title 995,Movie,Canada,Romance,TV-14,2019,2024-12-13,157,7.5
995,NF0996,Netflix Title 996,Movie,United Kingdom,Romance,PG-13,2014,2021-05-18,168,6.3
998,NF0999,Netflix Title 999,Movie,United Kingdom,Sci-Fi,R,2023,2025-02-22,169,7.6

In [36]:
df[df["Type"]=="TV Show"]

,Title_ID,Title,Type,Country,Genre,Rating,Release_Year,Date_Added,Duration_Minutes,IMDb_Rating
4,NF0005,Netflix Title 5,TV Show,India,Comedy,R,2013,2024-01-10,6,7.9
6,NF0007,Netflix Title 7,TV Show,Brazil,Thriller,TV-PG,2012,2020-07-06,4,8.6
11,NF0012,Netflix Title 12,TV Show,Canada,Crime,R,2024,2021-08-08,5,6.1
12,NF0013,Netflix Title 13,TV Show,Brazil,Sci-Fi,PG,2022,2024-01-22,4,9.5
14,NF0015,Netflix Title 15,TV Show,Brazil,Comedy,R,2022,2025-04-01,9,6.5
...,...,...,...,...,...,...,...,...,...,...
990,NF0991,Netflix Title 991,TV Show,South Korea,Action,TV-14,2011,2020-09-17,6,7.2
993,NF0994,Netflix Title 994,TV Show,India,Comedy,PG,2013,2020-06-20,9,5.9
996,NF0997,Netflix Title 997,TV Show,United States,Thriller,R,2020,2023-03-20,9,6.2
997,NF0998,Netflix Title 998,TV Show,South Korea,Sci-Fi,PG-13,2017,2021-09-12,9,7.2
999,NF1000,Netflix Title 1000,TV Show,United States,Crime,TV-14,2010,2025-10-20,2,5.8

In [37]:
df[df["IMDb_Rating"]>8]

,Title_ID,Title,Type,Country,Genre,Rating,Release_Year,Date_Added,Duration_Minutes,IMDb_Rating
3,NF0004,Netflix Title 4,Movie,United Kingdom,Sci-Fi,PG-13,2018,2021-09-28,87,9.3
6,NF0007,Netflix Title 7,TV Show,Brazil,Thriller,TV-PG,2012,2020-07-06,4,8.6
7,NF0008,Netflix Title 8,Movie,Canada,Comedy,R,2018,2025-01-31,141,8.8
12,NF0013,Netflix Title 13,TV Show,Brazil,Sci-Fi,PG,2022,2024-01-22,4,9.5
16,NF0017,Netflix Title 17,TV Show,United States,Documentary,PG,2015,2025-09-10,2,9.0
...,...,...,...,...,...,...,...,...,...,...
984,NF0985,Netflix Title 985,Movie,Japan,Sci-Fi,R,2013,2025-07-19,139,9.3
986,NF0987,Netflix Title 987,TV Show,Canada,Animation,TV-14,2020,2025-04-02,3,9.0
987,NF0988,Netflix Title 988,TV Show,Spain,Romance,R,2015,2022-04-28,5,8.3
991,NF0992,Netflix Title 992,Movie,India,Animation,TV-14,2025,2022-11-22,103,8.6
992,NF0993,Netflix Title 993,Movie,Germany,Documentary,TV-14,2013,2020-07-25,178,9.3

In [38]:
df[df["Country"]=="India"]

,Title_ID,Title,Type,Country,Genre,Rating,Release_Year,Date_Added,Duration_Minutes,IMDb_Rating
4,NF0005,Netflix Title 5,TV Show,India,Comedy,R,2013,2024-01-10,6,7.9
15,NF0016,Netflix Title 16,Movie,India,Animation,PG-13,2020,2021-04-01,97,7.2
26,NF0027,Netflix Title 27,Movie,India,Comedy,TV-PG,2023,2023-12-22,114,7.1
27,NF0028,Netflix Title 28,Movie,India,Drama,R,2020,2021-03-23,91,6.3
38,NF0039,Netflix Title 39,Movie,India,Animation,TV-14,2018,2021-06-26,179,6.9
...,...,...,...,...,...,...,...,...,...,...
945,NF0946,Netflix Title 946,TV Show,India,Drama,R,2014,2023-08-17,7,8.2
956,NF0957,Netflix Title 957,Movie,India,Romance,TV-MA,2016,2023-03-09,83,8.8
962,NF0963,Netflix Title 963,Movie,India,Animation,PG,2022,2021-01-14,111,6.5
991,NF0992,Netflix Title 992,Movie,India,Animation,TV-14,2025,2022-11-22,103,8.6
993,NF0994,Netflix Title 994,TV Show,India,Comedy,PG,2013,2020-06-20,9,5.9

## Sorting

In [39]:
df.sort_values(
"IMDb_Rating",
ascending=False
)

,Title_ID,Title,Type,Country,Genre,Rating,Release_Year,Date_Added,Duration_Minutes,IMDb_Rating
276,NF0277,Netflix Title 277,Movie,Canada,Action,R,2014,2025-02-06,155,9.5
450,NF0451,Netflix Title 451,Movie,Canada,Thriller,TV-14,2011,2024-09-30,70,9.5
469,NF0470,Netflix Title 470,TV Show,Germany,Horror,R,2013,2020-01-31,9,9.5
412,NF0413,Netflix Title 413,TV Show,India,Horror,PG,2018,2020-11-03,1,9.5
37,NF0038,Netflix Title 38,TV Show,France,Romance,TV-MA,2010,2025-02-20,10,9.5
...,...,...,...,...,...,...,...,...,...,...
69,NF0070,Netflix Title 70,TV Show,Spain,Horror,TV-PG,2010,2024-04-07,8,5.5
765,NF0766,Netflix Title 766,TV Show,Spain,Romance,TV-14,2015,2024-10-05,10,5.5
388,NF0389,Netflix Title 389,Movie,Japan,Action,TV-MA,2010,2021-07-16,149,5.5
324,NF0325,Netflix Title 325,TV Show,United Kingdom,Sci-Fi,PG-13,2021,2021-03-12,2,5.5
724,NF0725,Netflix Title 725,TV Show,France,Action,PG,2017,2023-04-04,4,5.5

## Correlation

In [40]:
df.corr(numeric_only=True)

                  Release_Year  Duration_Minutes  IMDb_Rating
Release_Year          1.000000         -0.056371     0.014932
Duration_Minutes     -0.056371          1.000000     0.004733
IMDb_Rating           0.014932          0.004733     1.000000

In [41]:
df[["Duration_Minutes","IMDb_Rating"]].corr()

                  Duration_Minutes  IMDb_Rating
Duration_Minutes          1.000000     0.004733
IMDb_Rating               0.004733     1.000000

## Outlier Detection

In [42]:
Q1 = df["IMDb_Rating"].quantile(0.25)

Q3 = df["IMDb_Rating"].quantile(0.75)

IQR = Q3-Q1

lower = Q1-1.5*IQR

upper = Q3+1.5*IQR

df[
(df["IMDb_Rating"]<lower)
|
(df["IMDb_Rating"]>upper)
]

Empty DataFrame
Columns: [Title_ID, Title, Type, Country, Genre, Rating, Release_Year, Date_Added, Duration_Minutes, IMDb_Rating]
Index: []